### ISSUE TITLE
Nefungující vyhodnocení

### ISSUE THREAD

**Issue by elendirx** [MarieFardova/byliny#1]
Podle mně by mělo stačit indexovat správné odpovědi od nuly namísto od jedničky, např. tady by měla být jednička místo dvojky.

https://github.com/MarieFardova/byliny/blob/a32f278a05cfee38f9b6c17759e3cb488bf52b34/index.js#L6

**Comment by MarieFardova** [comment]
Děkuji, už to funguje.
